### ISSUE TITLE
problem with background class in about page

### ISSUE THREAD

**Issue by xagon** [tomastrajan/angular-ngrx-material-starter#1]
Hi,
Nice template. Found an issue tho with the about.component.scss .background &::before class.
If you maximize the window - the mountains picture is displayed properly. When you make the browser much smaller, the problem happens when you scroll down in the menu. The toolbar and footer are fixed, but the image is set to a fixed size as well. See screenshots:
![about - in maximized window](https://user-images.githubusercontent.com/20299573/27927043-bc852fa4-628a-11e7-8af6-adc5d868c05b.png)
![about - in browser window shrinked - scrollbar on top](https://user-images.githubusercontent.com/20299573/27927044-bc882da8-628a-11e7-89fd-05b97216a5c3.png)
![about - in browser window shrinked - scrollbar moved a little down](https://user-images.githubusercontent.com/20299573/27927045-bc8c8ba0-628a-11e7-9bfc-e5ab09426c1f.png)

At this stage I am not sure how to fix it. I tested couple of ideas, but no solution yet. Potentially, another div which will cover the resizing, or changing the background & &behind classes?

Regards,
Kuba

**Comment by tomastrajan** [comment]
Hey Kuba,

thanks for the catch! Yeah I think another div with something like `height: 100vh` should help. Feel free to submit your PR if you can solve it! ;)

Wish you a great day!

**Comment by tomastrajan** [comment]
Hey Kuba,

if fixed the issue, now it should work no matter the window size :)
