### ISSUE TITLE
[Feature Request] Using ngrx/entity

### ISSUE THREAD

**Issue by lexcaraig** [tomastrajan/angular-ngrx-material-starter#12]
It would be great to add the new `ngrx/entity` feature and provide an example. So we can follow the latest update provided by ngrx. :)

Over all, this is a really good starter. :)

**Comment by tomastrajan** [comment]
Was not aware of that one, will definitely look into it and let you know.

**Comment by lexcaraig** [comment]
Great! Looking forward on it! Thanks! :)

**Comment by tomastrajan** [comment]
I was looking into it and its very specific to the CRUD operations which are not really present in the starter project as of now. Therefore there is no reason to add @ngrx/entity as of current starter project scope.
