### ISSUE TITLE
Why not OnPush change detection in BigInputActionComponent?

### ISSUE THREAD

**Issue by hhubik** [tomastrajan/angular-ngrx-material-starter#126]
Thanks for making this starter project!!

I am wondering though why none of the components use OnPush change detection. I am under the impression that one of the benefits of using "dumb" components that only receive input data and/or produce output data was that their performance could be improved by  using the OnPush change detection.

It seems that at the very least `BigInputActionComponent`  and perhaps `AboutComponent` should use OnPush change detection. Any thoughts on this?

**Comment by hhubik** [comment]
@tomastrajan I will give that a try.

**Comment by tomastrajan** [comment]
Closed by #134 , thanks again @hhubik !

**Comment by hhubik** [comment]
No problem. Glad to help!
