### ISSUE TITLE
[Suggestion] Provide sample integration with firestore

### ISSUE THREAD

**Issue by zoamel** [tomastrajan/angular-ngrx-material-starter#131]
I want to suggest providing some sample integration with firestore + ngrx, maybe on some branch. I think it's quite popular BaaS and some people will try to use it, especially for some MVP concepts. And from what I see integrating this with ngrx is not very trivial so this would help a lot to see your sample implementation :)

**Comment by tomastrajan** [comment]
All contributions are very welcome and appreciated! They can be used as a basis to community effort to improve and enhance!

**Comment by ZackDeRose** [comment]
Has there been any further discussion/thought on this? My initial that is to create a simple Firebase backend for the Todo list. I think though that you probably wouldn't want to open that up (e.g. you'd probably want working auth stuff first). @tomastrajan would you be open to using firebase auth in this project?

**Comment by tomastrajan** [comment]
@ZackDeRose definitely, auth stuff is extremely basic, basically does nothing just demonstrates auth guard but there is no handling of the auth besides setting a `boolean` flag. Please, feel free to propose solution.

**Comment by tomastrajan** [comment]
This is out of scope for the starter. (Old issue cleanup)
