### ISSUE TITLE
angular/cli dependency looks incorrect (latest is 1.7.4)

### ISSUE THREAD

**Issue by shootermv** [tomastrajan/angular-ngrx-material-starter#132]

**Comment by tomastrajan** [comment]
The latest release was about increasing all Angular related versions to 6.0.0-rc or similar to be able to use new Angular CLI project layout (with new `angular.json` config file), new RxJS version with pipeable operators by default (and a new way of importing operators) and so on.

Does this answer your question?

**Comment by shootermv** [comment]
Sorry. Saw now at cli changelog that they changed the versions to be like
the angular ones... I was wrong. Sorry again

**Comment by tomastrajan** [comment]
No worries mate, thank for your contribution and interest!
