### ISSUE TITLE
Why barrel files?

### ISSUE THREAD

**Issue by hhubik** [tomastrajan/angular-ngrx-material-starter#133]
Barrel files are no longer recommended by the Angular team:

> Barrels now [after introduction of ngModules] are far less useful and have been removed from the [Angular] style guide

`angular-ngrx-material-starter/src/app/core/index.ts`
`angular-ngrx-material-starter/src/app/shared/index.ts` 

In my experience, barrel files can lead to problems due to circular dependencies.  Any thoughts on that?

**Comment by tomastrajan** [comment]
Can you please provide link to that statement? I only could find [this](https://angular.io/guide/glossary#barrel).

As for circular dependencies, their presence can be a valuable signal that the service / something which is affected should be moved up in the hierarchy or refactored so I don't see this as a bad thing.

Also I guess circular dependencies happen more because of the way the functionality is structured and not because of the use of barrel itself but my experience whit that is limited.

**Comment by hhubik** [comment]
@tomastrajan  search for `barrel` in [Angular Changelog](https://angular.io/guide/change-log)

**Comment by tomastrajan** [comment]
I have checked the discussion and think that the last comment summarizes it quite nicely...

> @michaeljota We all like barrels. What has changed is that they are now considered a matter of personal style, not Angular style.
> 
> There was a time when we thought they would be almost essential for aggregating access to components. After modules were introduced, that purpose melted away. **They still have utility for aggregating model and service classes;** I'm sure they are useful elsewhere too.
> 
> SystemJS is not a factor in this decision. Barrels and SystemJS get along fine.
> 
> **Keep using barrels as you find them helpful.** We have decided not to restore barrels to the Style Guide. This issue is closed.

(emphasis is mine)

Barrels can still be useful for simplification of import / export of a module with a lot of stuff (eg: services) which will be imported by other services / components / modules. The `CoreModule` and it's `index.ts` file are then a great example of a barrel which exposes services which are needed by many other services through the application. 

Hope that this helps!

Thank you for your interest and contribution!

**Comment by jeevasusej** [comment]
Can we use barrels only for interfaces, classes or enums instead of services, directives or components?

**Comment by cvidevelopment** [comment]
b
