### ISSUE TITLE
Blocking at emitting LicenseWebpackPlugin when npm start.

### ISSUE THREAD

**Issue by lizhigang858** [tomastrajan/angular-ngrx-material-starter#139]
```
** Angular Live Development Server is listening on localhost: 4200, open your browser on http://localhost:4200/ **
 95% emitting LicenseWebpackPlugin    
```

**Comment by fealonelei** [comment]
@lizhigang858  Hi, from your name, I guess you are from China, and perhaps, you are using `cnpm install` instead of `npm install`, which cause your issues. Maybe it's cnpm's bug or something. just use `npm install`, issue gone.

**Comment by railsbug** [comment]
it's real....
i use lantern
and everything is ok

**Comment by tomastrajan** [comment]
Added `Troubleshooting` sectiomn to README.md.
