### ISSUE TITLE
pug support

### ISSUE THREAD

**Issue by spairo** [tomastrajan/angular-ngrx-material-starter#140]
Hi guys, somebody knows how to avaible the pug/jade templating support?

Regards.

**Comment by tomastrajan** [comment]
I suppose most user of this repository will want to follow standard `.html` way provided by Angular CLI by default.  As for pug support please have a look at [this article](https://hackernoon.com/using-pug-jade-with-angular-with-cli-5592b7ee24e6).

Cheers!
