### ISSUE TITLE
Google Analytics Pageview Tracking

### ISSUE THREAD

**Issue by philmerrell** [tomastrajan/angular-ngrx-material-starter#173]
Thanks for the wonderful work on this starter. We have forked it to use as a base at my institution and it has saved us a lot of time.

I noticed that you embedded the Google Analytics tracking code in the starter app, which is great, but due to the nature of single page applications, it is only tracking the initial load of index.html. In order to track each page view you must subscribe to the `NavigationEnd` router event and manually push each pageview to Google Analytics.

I'm creating a PR to primarily address the pageview issue, however, there is quite a lot going on in the `ngOnInit` method in `app.component.ts`, so I refactored for clarity and readability. If there is a particular style or refinement you'd like in the PR, I'd be happy to oblige.

**Comment by tomastrajan** [comment]
Hi @philmerrell !

I am very happy to hear that you could use this starter project in real world app. Is it public? If so would you consider adding link to [BUILD_WITH.md](https://github.com/tomastrajan/angular-ngrx-material-starter/blob/master/BUILT_WITH.md) ?

The improvement with tracking pages is great! Also refactoring part is more than welcome. It grew over time and to be honest I was a bit lazy to clean it up so thanks again!

The only thing is the [failing build](https://travis-ci.org/tomastrajan/angular-ngrx-material-starter/builds/370400816#L530) which will will be solved by running `npm run prettier` before commit. I suppose I should automate that with a pre-commit hook later.

Cheers !

**Comment by philmerrell** [comment]
I was happy to contribute and I'll look for more opportunities in the future. This is by far my favorite starter!

I work for a public university, and getting things into production takes months typically. When the time comes I'd be happy to add to BUILD_WITH.md.

**Comment by tomastrajan** [comment]
Looking forward to the merging of the BUILD_WITH.md PR 😉 Thanks again!
