### ISSUE TITLE
Improve / add more e2e test

### ISSUE THREAD

**Issue by tomastrajan** [tomastrajan/angular-ngrx-material-starter#178]
This repository currently runs single e2e test as a part of it's CI (continuous integration) build on Travis CI. Test can also be executed using `npm run e2e`.

It would be great to provide more e2e test examples for the users of this repository to serve as a great example for how to write their own tests.

- best practices for angular e2e testing ( eg: separate tests and page objects ... )
- more e2e test (mostly for the examples functionality) like add todo, toggle todo, ...
- suggest / evaluate / use community driven e2e test library for angular

Tests can be added in step by step fashion with one PR corresponding to the tests of one route / page to keep the required effort low but please feel free to add more ;)

ps: please use commit message in format like feat(e2e): add <test-description > tests, #<issue-number>, just replace test description with stuff like "todos" based on applicable route / page.

**Comment by christophechevalier** [comment]
In my app, I use this front-end testing tool : 

> https://www.cypress.io/

**Comment by tomastrajan** [comment]
Closing this issue because it is too generic, will open additional issues (one per component / feature) to better track progress and to introduce ability to close issues with the commit message.
