### ISSUE TITLE
[Feature request] Universal support.

### ISSUE THREAD

**Issue by ahaw** [tomastrajan/angular-ngrx-material-starter#2]
As a AngularCli added support for Universal app angular-ngrx-material-starter should have option to be build with support for Angular Universal to achieve better seo.

**Comment by tomastrajan** [comment]
That's definitely something I will look into in the future!

**Comment by tomastrajan** [comment]
Angular Cli 1.3.0 supports SSR but it's still unfinished and doesn't support lazy routes so I'll will wait until that is supported. Check the SRR [guide](https://github.com/angular/angular-cli/wiki/stories-universal-rendering) from Angular Cli.

**Comment by tomastrajan** [comment]
As commented on the related PR

**Comment by Amitshaale** [comment]
hi
