### ISSUE TITLE
Move shared/common used code into library for multiple projects workspace

### ISSUE THREAD

**Issue by hungcao181** [tomastrajan/angular-ngrx-material-starter#216]
With CLI v6 we now have options to maintain multiple projects in a monospace.
Currently when I add a new project with help of cli v6 into the this starter code base, I could not use any code provided here

**Comment by tomastrajan** [comment]
This is definitely something worth exploring!

I haven't worked with Angular CLI 6 too much yet. I am aware that `nrwl/nx` has support for monorepos and generation of libraries. Don't know about how much support is available when using Angular CLI 6 only without the help of 3rd party libraries.

I would definitely be interested in extracting `shared` as a library if it is supported. But I am worried about the implication to the release process, npm integration etc. Is is possible to set it up still as a single project with apps which actually don't have to be released separately?

In that case we would end up with single project with single release version in single package.json containing multiple Angular CLI apps and libraries. 

The question is then if it even makes sense to have it like that when we don't support separate release cycle for the included apps and libraries...

Any thoughts on this ?

**Comment by ohizkiya** [comment]
Would love to see a similar idea taken a step further and have the entire project be consumable as a framework by other apps, giving them the ability to continue to pull in changes as a updates are made to the starter. (It would morph into a true framework rather than a hard-fork from a starter, which is ideal.) From what I can tell there are still some rough edges around making this happen in Angular 6 (need to manually build scss and manually copy assets) but I think it's both workable and a process that will be improved soon.

**Comment by felixunivers** [comment]
First of all, THANK YOU for this great project. I have learned a lot from it.
As this project is intended as a "starter" it could be a fantastic base for many projects.
I would picture its structure a bit less monolithic and rather more "library-tic", where inside a single workspace we would have library projects, app projects and test projects. The users would easily incorporate the libraries to their own components, which could be based on the "starter" front end examples with user's own modifications. 
I would also recommend a bit more detailed documenting / commenting in the code for the programmers (especially beginners) to be able to follow the code logic.

**Comment by tomastrajan** [comment]
There are no plans to do this currently. (Old issue cleanup)
