### ISSUE TITLE
ng generate not working

### ISSUE THREAD

**Issue by gauravmakkar** [tomastrajan/angular-ngrx-material-starter#222]
I'm trying to run angular cli commands like **ng generate component hello** and it changes nothing.

**Comment by tomastrajan** [comment]
Hi @gauravmakkar !

Could you please provide some error console output or anything else? I just tried it locally and everything worked as expected.

Cheers!

**Comment by gauravmakkar** [comment]
My bad. I guess the issue was this angular-cli installation. Re-installed it and working fine now.

**Comment by tomastrajan** [comment]
Happy to hear that you resloved your problem!
