### ISSUE TITLE
Create unit tests for stock-market component.

### ISSUE THREAD

**Issue by tomastrajan** [tomastrajan/angular-ngrx-material-starter#243]
Create unit test for stock market component that covers its functionality.

Please follow testing pattern introduced in [todos.component.spec.ts](https://github.com/tomastrajan/angular-ngrx-material-starter/blob/master/src/app/examples/todos/todos.component.spec.ts) or please suggest improvements in the comments.

TESTS (rough idea, please adjust / improve where makes sense):

should show spinner if stocks are loading
should hide spinner if stocks are loaded
should show error on retrieve stocks error
should display stock (name, price, change, exchange)
should dispatch retrieve action on symbol input change
...

Feel free to check out [Contributors Guide](https://github.com/tomastrajan/angular-ngrx-material-starter/blob/master/CONTRIBUTING.md) for useful tips and hints that help you get started.

**Comment by alexkonovalov** [comment]
I’m picking this one up. Expect the PR soon :)

**Comment by tomastrajan** [comment]
Hi @alexkonovalov ! 

Very happy to hear that, looking forward to the PR! 

ps: feel free to add more if you see some opportunities, I will create more issues for the tests of reducers, effects etc so that there is plenty of opportunity for the community to make the first contribution

**Comment by alexkonovalov** [comment]
@tomastrajan have you considered utilising the *BDD* approach like in the following snippet:
```
describe("given scenario", () => {
  beforeEach(() => {..})
  describe("when nested scenario", ()=>{
    ...
  }
  it("", () => {
    expect
  })
})
```
? In my opinion it could improve readability and reduce the code doubling for more complex cases. If you don't have any objections, I can try to format my test this way in the PR and we can have a follow-up discussion. Thank you!

**Comment by tomastrajan** [comment]
Sure, if there are enough cases so that the subdivision makes sense feel free to use it. In the original todos test file it was pretty simple and possible to start from the base setup for every test case.
