### ISSUE TITLE
Implement Typed Actions

### ISSUE THREAD

**Issue by Kaffiend** [tomastrajan/angular-ngrx-material-starter#25]
Instead of overriding the `Action` interface for `@ngrx` its a ver nice development experience having typed actions with models for the payload, with intellisense.

**Comment by tomastrajan** [comment]
Pull request maybe ? 😉

**Comment by tomastrajan** [comment]
Now follows official [ngrx actions guide](https://github.com/ngrx/platform/blob/master/docs/store/actions.md). Cheers 🎉
