### ISSUE TITLE
Create new "form" example

### ISSUE THREAD

**Issue by tomastrajan** [tomastrajan/angular-ngrx-material-starter#263]
The starter project contains lazy loaded examples module which currently contains following examples:

* todos 
* stock market
* theming
* auth only route

Create new example demonstrating "real life" complex reactive form using a form builder.

* should live in `examples/form` route
* should have dedicated component, reducer (effects if needed)

Form should have following features:

* record to be edited (eg user record with edit, save, reset button)
* use various input types (eg input, dropdown, slider, toggle)
* use unified "real life" like content (eg pizza creator, user editor, order creation or similar)
* use form validation with validation messages (eg required, email, more than ...)
* reset button ( to clear form to  original state )
...

Please feel free to suggest, enhance or improve anything!

Feel free to check out [Contributors Guide](https://github.com/tomastrajan/angular-ngrx-material-starter/blob/master/CONTRIBUTING.md) for useful tips and hints that help you get started.

**Comment by timdeschryver** [comment]
Closed via #317.
