### ISSUE TITLE
Create unit tests for todos effects

### ISSUE THREAD

**Issue by tomastrajan** [tomastrajan/angular-ngrx-material-starter#265]
Create tests for `todos.effects.ts` in `todos.effects.spec.ts` file either by following [official ngrx testing guide](https://github.com/ngrx/platform/blob/master/docs/store/testing.md) or feel free to suggest any improvements.

Try to keep tests as independent as possible (eg minimize importing of various modules in setting up tests)

Feel free to check out [Contributors Guide](https://github.com/tomastrajan/angular-ngrx-material-starter/blob/master/CONTRIBUTING.md) for useful tips and hints that help you get started.

**Comment by terrystrachan** [comment]
I'd like to take this one as my first ever contribution

**Comment by timdeschryver** [comment]
Awesome! Feel free to reach out if you need any help.

**Comment by terrystrachan** [comment]
thanks @timdeschryver 
Created a test similar to settings.effects.spec.ts for todos.effects.ts
Tests pass
CI passes
Going to create a pull request for review

**Comment by tomastrajan** [comment]
Ah, the commit message referenced the issue but didn't contain keyword like `closes` or `fixes` so I have to close issue manually, anyway @terrystrachan thanks again!
