### ISSUE TITLE
Create unit tests for stock market effects

### ISSUE THREAD

**Issue by tomastrajan** [tomastrajan/angular-ngrx-material-starter#267]
Create tests for `stock-market.effects.ts` in `stock-market.effects.spec.ts` file either by following [official ngrx testing guide](https://github.com/ngrx/platform/blob/master/docs/store/testing.md) or feel free to suggest any improvements.

Try to keep tests as independent as possible (eg minimize importing of various modules in setting up tests)

Feel free to check out [Contributors Guide](https://github.com/tomastrajan/angular-ngrx-material-starter/blob/master/CONTRIBUTING.md) for useful tips and hints that help you get started.

**Comment by lau32** [comment]
I'll can also take this one.

**Comment by zetsnotdead** [comment]
@lau32 are you taking a stab at this? If you're busy I could give it a shot this weekend :)

**Comment by tomastrajan** [comment]
@zetsnotdead I guess @lau32 is currently busy because it's a pretty long time since he commented without PR so feel free to submit a PR yourself ;)

**Comment by zetsnotdead** [comment]
Working on it :) Should have it ready tomorrow.
