### ISSUE TITLE
Create unit tests for stock market service

### ISSUE THREAD

**Issue by tomastrajan** [tomastrajan/angular-ngrx-material-starter#268]
Create tests for `stock-market.service.ts` in `stock-market.service.spec.ts` file by following [official Angular testing guide](https://angular.io/guide/testing#testing-http-services) or feel free to suggest improvements!

Feel free to check out [Contributors Guide](https://github.com/tomastrajan/angular-ngrx-material-starter/blob/master/CONTRIBUTING.md) for useful tips and hints that help you get started.

**Comment by lau32** [comment]
I can take this up.

**Comment by timdeschryver** [comment]
Closed via #344.
