### ISSUE TITLE
Create unit tests for settings reducer

### ISSUE THREAD

**Issue by tomastrajan** [tomastrajan/angular-ngrx-material-starter#269]
Create tests for `settings.reducer.ts` in `settings.reducer.spec.ts` file either by following [official ngrx testing guide](https://github.com/ngrx/platform/blob/master/docs/store/testing.md) or feel free to suggest any improvements.

Feel free to check out [Contributors Guide](https://github.com/tomastrajan/angular-ngrx-material-starter/blob/master/CONTRIBUTING.md) for useful tips and hints that help you get started.

**Comment by hhubik** [comment]
Hi @tomastrajan how is this?

`settings.reducer.spec.ts`:

```javascript
import {
    initialState,
    settingsReducer,
    ActionSettingsPersist,
    SettingsActionTypes,
    ActionSettingsChangeTheme,
    ActionSettingsChangeAnimationsPage,
    ActionSettingsChangeAnimationsPageDisabled,
    ActionSettingsChangeAnimationsElements,
    ActionSettingsChangeAutoNightMode
} from './settings.reducer';

describe('settingsReducer', () => {

    it('ActionSettingsPersist with undefined new state should return the initial state', () => {
        const action: ActionSettingsPersist = {
            type: SettingsActionTypes.PERSIST,
            payload: undefined
        };
        const state = settingsReducer(undefined, action);
        expect(state).toBe(initialState);
    });

    it('ActionSettingsChangeTheme should return state with updated theme', () => {
        const payload = { theme: 'dark' };
        const expectedState = { ...initialState, ...payload };
        const action: ActionSettingsChangeTheme = {
            type: SettingsActionTypes.CHANGE_THEME,
            payload: payload
        };
        const state = settingsReducer(undefined, action);
        expect(state).toEqual(expectedState);
    });

    it('ActionSettingsChangeAnimationsPage should return state with updated pageAnimations', () => {
        const payload = { pageAnimations: false };
        const expectedState = { ...initialState, ...payload };
        const action: ActionSettingsChangeAnimationsPage = {
            type: SettingsActionTypes.CHANGE_ANIMATIONS_PAGE,
            payload: payload
        };
        const state = settingsReducer(undefined, action);
        expect(state).toEqual(expectedState);
    });

    it('ActionSettingsChangeAnimationsPageDisabled should return state with updated pageAnimationsDisabled', () => {
        const payload = { pageAnimationsDisabled: true };
        const expectedState = { ...initialState, ...payload, pageAnimations: false };
        const action: ActionSettingsChangeAnimationsPageDisabled = {
            type: SettingsActionTypes.CHANGE_ANIMATIONS_PAGE_DISABLED,
            payload: payload
        };
        const state = settingsReducer(undefined, action);
        expect(state).toEqual(expectedState);
    });

    it('ActionSettingsChangeAnimationsElements should return state with updated elementsAnimations', () => {
        const payload = { elementsAnimations: false };
        const expectedState = { ...initialState, ...payload };
        const action: ActionSettingsChangeAnimationsElements = {
            type: SettingsActionTypes.CHANGE_ANIMATIONS_ELEMENTS,
            payload: payload
        };
        const state = settingsReducer(undefined, action);
        expect(state).toEqual(expectedState);
    });

    it('ActionSettingsChangeAutoNightMode should return state with updated autoNightMode', () => {
        const payload = { autoNightMode: true };
        const expectedState = { ...initialState, ...payload };
        const action: ActionSettingsChangeAutoNightMode = {
            type: SettingsActionTypes.CHANGE_AUTO_NIGHT_AUTO_MODE,
            payload: payload
        };
        const state = settingsReducer(undefined, action);
        expect(state).toEqual(expectedState);
    });

});

```

**Comment by tomastrajan** [comment]
Hi @hhubik ! Thank you for your contribution. I gave it some thought and it would be better that instead of large comment we stick to the standard git workflow of creating PR as a base for discussion because it enables to create comments on particular lines of code, what do you think? This one is ok but for the future ;)

As for the implementation, pretty ok but let's use available action classes to create actions. Also it would be better to test for expected state more in detail and isolation. The thing is that this reducer is very simple so basically it really just set properties so it does exactly the same as you in `const expectedState = { ...initialState, ...payload };`. Not every reducer will be that simple (or stay that simple) and the expected state will not map exactly to initial state + spreaded payload. 

Please have a look on the [todos.reducer.spec.ts](https://github.com/tomastrajan/angular-ngrx-material-starter/pull/279/files).

It uses available action creation classes and it tests for particular change.
In our case this would lead to code which looks something like this...

```typescript
    it('ActionSettingsChangeAnimationsPage should return state with updated pageAnimations', () => {
        const action = new ActionSettingsChangeAnimationsPage ({ pageAnimations: false });
        const state = settingsReducer(undefined, action);
        expect(state.pageAnimations).toEqual(false);
    });
```
The test doesn't make assumption about the other state properties so they can change independently. It is only testing the the `pageAnimations` functionality.

What are your thoughts ?

**Comment by hhubik** [comment]
@tomastrajan - Thanks for the feedback.  That makes sense.  I have updated the tests per your suggestion and opened a PR.

**Comment by hhubik** [comment]
Hi @tomastrajan - I followed the `rebase` steps from your message above.  I think it worked. At least I did not see any errors.  However, I don't think the Travis CI build ran after I did `git push -f`.  Let me know if there is anything else I should do.

**Comment by tomastrajan** [comment]
Hi @hhubik it worked perfectly, there is a single commit in the PR with the most recent comment and [Travis CI build](https://travis-ci.org/tomastrajan/angular-ngrx-material-starter/builds/405808871?utm_source=github_status&utm_medium=notification) did run! You can also see green tick next to updated commit in the bottom of the [PR page](https://github.com/tomastrajan/angular-ngrx-material-starter/pull/284). Thank you for your contribution!
