### ISSUE TITLE
Create unit tests for settings effects

### ISSUE THREAD

**Issue by tomastrajan** [tomastrajan/angular-ngrx-material-starter#270]
Create tests for `settings.effects.ts` in `settings.effects.spec.ts` file either by following [official ngrx testing guide](https://github.com/ngrx/platform/blob/master/docs/store/testing.md) or feel free to suggest any improvements.

Try to keep tests as independent as possible (eg minimize importing of various modules in setting up tests)

Feel free to check out [Contributors Guide](https://github.com/tomastrajan/angular-ngrx-material-starter/blob/master/CONTRIBUTING.md) for useful tips and hints that help you get started.

**Comment by hhubik** [comment]
I will give this and #269 a try.

**Comment by tomastrajan** [comment]
@hhubik great! Looking forward to PR / comments ;)

**Comment by hhubik** [comment]
Hi @tomastrajan - started looking into this and found a bunch of reducer tests that are already in `settings.component.spec.ts`.  Is this not complete?  If so, should I be adding to this spec file or should I create a new file `settings.reducer.spec.ts` in the same directory where `settings.reducer.ts` file is? Thanks.

**Comment by hhubik** [comment]
... at a high level, is this what we want?

`/settings/settings/settings.component.spec.ts` contain only tests simulating how the `SettingsComponent` would be used from the UI, whereas

`/settings/settings.reducer.spec.ts` would test exhaustively just the reducer functions

Similarly, 
`/setting/settings.effects.spec.ts` would focus only on testing the PERSIST action effect?
