### ISSUE TITLE
cant start stackblitz app

### ISSUE THREAD

**Issue by laurencefass** [tomastrajan/angular-ngrx-material-starter#276]
this stackblitz version is not failing in both chrome and firefox. not sure if you are maintaining but guessing yes.

https://stackblitz.com/edit/angular-ngrx-material-starter

After loading, reports 
```
Can't find packages:
@app/shared
@app/core
@env/environment
```

> prompt: install missing packages?

click yes....

`unable to find package @app/shared.
`
many thanks

**Comment by tomastrajan** [comment]
Hi @laurencefass!

This is a know issue with StackBlitz not being able to evaluate `paths` property in `tsconfig.json` which is used to create aliases for module imports.

I made them aware of this issue some months ago but they haven't solved it yet :(

If you want to make it work you can replace all `@app` , `@env` and `@testing` aliases with relative paths.

The relative paths will not be used in this repo by default. StackBlitz, while nice is not the default development environment for most people and having aliases is very convenient for development and it also helps with understanding and structuring of the dependencies (vendor vs app libs vs local relative).

Hope that helps!

**Comment by tomastrajan** [comment]
@laurencefass happy to help!
