### ISSUE TITLE
Dialogs not working correctly

### ISSUE THREAD

**Issue by Gerrilicious** [tomastrajan/angular-ngrx-material-starter#281]
Hey im using your project as template and I noticed it seems kind of hard to show a dialog as done by material angular

I am not sure how to style the dialog, can you help?

Result:
![image](https://user-images.githubusercontent.com/23362230/42515125-4e0d8e60-845b-11e8-8343-e997540b3521.png)

Code:
Clickhandler for opening Dialog;
![image](https://user-images.githubusercontent.com/23362230/42515459-1a15ddf0-845c-11e8-91c8-0f734f72baf6.png)

Dialog-component: 
![image](https://user-images.githubusercontent.com/23362230/42515575-5d9276ce-845c-11e8-8bdb-7c2e17da8453.png)

Dialog-component-html:
![image](https://user-images.githubusercontent.com/23362230/42515630-8947ed80-845c-11e8-8c77-e21bf367ca70.png)

Thanks in Advance!

**Comment by hhubik** [comment]
@Gerrilicious perhaps [this Angular Material example](https://material.angular.io/components/dialog/examples) helps?

**Comment by Handavipul** [comment]
//code for parent component 
  constructor(public dialogRef: MatDialogRef<UserProfileComponent>,
  @Inject(MAT_DIALOG_DATA) public data: any) {}

openDialog(): void {
   const dialogRef = this.dialog.open(ComponentName, {
    height: '500px',
    width: '400px',
     data: {UserInfo : 'data to be displayed' }
   });

**Comment by tomastrajan** [comment]
Hope you could find solution to your problem. (Old issue cleanup)
