### ISSUE TITLE
Lint warning "source is deprecated" in utils.ts line 25

### ISSUE THREAD

**Issue by hhubik** [tomastrajan/angular-ngrx-material-starter#299]
I am getting the following warning from `ng lint` on my Windows 8.1 development system:

`WARNING: D:/Users/hubert/Documents/Angular2Dev/poltrack/src/testing/utils.ts[25, 10]: source is deprecated: This is an internal implementation detail, do not use.`

Any ideas on how to fix this?

**Comment by tomastrajan** [comment]
Hi @hhubik thank you for the catch! @timdeschryver any ideas about this what is the plan of ngrx team? Can we keep using this until they provide their own `MockStore` as in that PR you shared before or ?

**Comment by timdeschryver** [comment]
I tried working around the internal source, but I don't know if it's possible, because NgRx also uses this source in the store (store.ts#L19)[https://github.com/ngrx/platform/blob/master/modules/store/src/store.ts#L19]. 
I would say put this on hold till we got it fixed in NgRx.

**Comment by timdeschryver** [comment]
Fyi, in NgRx 7 there will be a `MockStore` - https://github.com/ngrx/platform/blob/master/CHANGELOG.md#features

**Comment by tomastrajan** [comment]
Soon ! :D

**Comment by tomastrajan** [comment]
This was solved by the migration to Angular / NgRx 8 and refactoring tests to use ngrx `MockStore`.
