### ISSUE TITLE
Create proper AppState

### ISSUE THREAD

**Issue by tomastrajan** [tomastrajan/angular-ngrx-material-starter#304]
Create `AppState` and use it for:
* stores in the app as in `Store<AppState>`
* createState helper in tests
* somewhere else ?

Verify that imports of interfaces across lazy loaded module boundaries don't cause unexpected content in the bundles. Verify with `npm run analyze`.

**Comment by tomastrajan** [comment]
Hi @timdeschryver , I just finished refactoring of selectors used in examples module so now we can proceed with this, will you have a look ?

**Comment by timdeschryver** [comment]
@tomastrajan I will 😄
