### ISSUE TITLE
Footer no longer stick to the bottom when i use ngx-perfect-scrollbar

### ISSUE THREAD

**Issue by cloudstr21** [tomastrajan/angular-ngrx-material-starter#307]
Hi there,

I am sorry, missed this part, so I edited the descriptions.
Footer always at the bottom as expected, but when I use ngx-perfect-scrollbar, the footer is no longer stay at the bottom. They raised to the top depending on the size of the content.

app.component.html and app.component.scss still the same. the only changes are I added perfect-scrollbar tag as followed below:

> <div class="wrapper">
    <perfect-scrollbar>
      <div class="content">
        <router-outlet></router-outlet>
      </div>
      <div class="footer">
        <div class="row">
          <div class="col-12 signature">
          </div>
        </div>
      </div>
    </perfect-scrollbar>
  </div>

Do you have any ideas? 
Please help me. 
Thanks

Ronald

**Comment by aideslucas** [comment]
Hi @cloudstr21 ,
never used perfect-scrollbar myself, and wasnt able to test this myself,
seems to me you need to take the footer out of the perfect scrollbar like this:

```
<perfect-scrollbar>
  <div class="content">
    <router-outlet></router-outlet>
  </div>
</perfect-scrollbar>
  <div class="footer">
    <div class="row">
      <div class="col-12 signature">
      </div>
    </div>
  </div>
```

let me know if this helped

**Comment by cloudstr21** [comment]
Hi @aideslucas ,
Thank you for your commented. I have tried that one and footer become fixed, so the scrollbar only inside the content.
I also tried to add min-height: 100vh, into class below
 `.content {
      position: relative;
      flex: 1 0 auto;
      
      min-height: 100vh;
    }`
but the result still not the expected one.

**Comment by tomastrajan** [comment]
I hope you could find the solution! This is a 3rd party lib specific problem.
