### ISSUE TITLE
yarn or npm

### ISSUE THREAD

**Issue by FabienDehopre** [tomastrajan/angular-ngrx-material-starter#308]
It appears that the repo contains both a `yarn.lock` file and a `package-lock.json` file.
As quoted by yarn:
> It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files.

Which one should we use? Yarn or NPM?

**Comment by tomastrajan** [comment]
Hi @FabienDehopre ! 

The default package manager for this repo is `npm`.

The `yarn.lock` file was added by other contributor some time in the past but was not kept in sync and I will remove it. 

Everyone is anyway free to use package manager of their choice in their own fork / clone.

**Comment by tomastrajan** [comment]
Fixed

**Comment by timsar2** [comment]
By using pnpm package manager it has an error:

`NullInjectorError: R3InjectorError(M1)`
