### ISSUE TITLE
Handle private browser window

### ISSUE THREAD

**Issue by hhubik** [tomastrajan/angular-ngrx-material-starter#318]
Just tried the app in a Chrome Incognito window.  Not surprisingly, the app state (settings, todos) is not persisted.  Should the app detect that it is running in a private window and either not start or at least warn the user that the state is not getting persisted?

**Comment by timdeschryver** [comment]
Personally I wouldn't change any of it, I believe this is the default and wanted behavior.

**Comment by hhubik** [comment]
I know plenty of paranoid people who browse in a private window by default.  It seems a bit odd that if they enter 10 todos and re-start their browser, the todos will not come back. This does not seem like the wanted behavior. Maybe they assumed the todos got saved somewhere on a server.

But I understand this might not be a problem to solve in the starter project.

**Comment by timdeschryver** [comment]
Yep, I agree.

**Comment by hhubik** [comment]
The local storage might be unavailable for other reasons besides running in a private window such being over the quota or being disabled.  There is a discussion of this topic [here](https://gist.github.com/paulirish/5558557).

Nevertheless, I am closing this as out-of-scope for the starter project.

**Comment by hhubik** [comment]
@tomastrajan @timdeschryver  a few more on questions on this.  The fact that the app did not give the slightest indication of the todos not getting stored (or not getting retrieved in the new window) still does not feel completely right to me, even for a starter project.  If the todos were not getting stored, shouldn't the app at least throw an exception?

In a more generic sense, should the project provide (eventually) some kind of infrastructure for error handling & logging?

**Comment by timdeschryver** [comment]
> In a more generic sense, should the project provide (eventually) some kind of infrastructure for error handling & logging?

We could do this, thoughts @tomastrajan ?

@hhubik Is there a way to detect this? Because your private window will store its todos in its own private localStorage as far as I know, meaning it won't throw an error.

**Comment by tomastrajan** [comment]
@timdeschryver definitely yes! I was previously thinking about centralized (core) infrastructure for notifications which would go very well hand in hand with this concepts. Please feel free to introduce this functionality!

Also as a side note, I am currently moving and searching for job so it's a bit hectic with less time for the OSS but I guess it should be all back to normal in the beginning of October.

Anyway, thank you guys!

**Comment by timdeschryver** [comment]
A HttpInterceptor is indeed very useful to handle http requests, we're using it within our applications at work. The same counts for creating a custom `ErrorHandler`.

We can add it, but I don't know if we'll run into these problems within this starter project. On the other hand if we add it, we also have the error handling side covered.

Do you want to open up a PR for one of these items @hhubik ?

**Comment by timdeschryver** [comment]
Yep that would probably be for the best, instead of one PR split it up into multiple small chunks. 
You can create the issue, but I was asking if you'd also want to write the code and open a PR.
