### ISSUE TITLE
Handle Http Service errors in StockMarket example

### ISSUE THREAD

**Issue by hhubik** [tomastrajan/angular-ngrx-material-starter#321]
Per the discussion in #318 ...

> Http Errors (e.g. server unavailable, timeouts, etc. These could be handled for example using the HttpInterceptor as explained in this [video](https://youtu.be/tS1CG4Qx5ow).

**Comment by timdeschryver** [comment]
Yep, as far I know I think you're right and that this is indeed the only place using `HttpClient`.

**Comment by hhubik** [comment]
@timdeschryver  Sorry for the delay.  I am swamped with other work.  I will get to this in a few days.

**Comment by timdeschryver** [comment]
Hey @hhubik no worries take your time 😄

**Comment by hhubik** [comment]
@timdeschryver  @tomastrajan 
Since I am not much of a UI guy, can you suggest an acceptable error notification mechanism for the UI.  Alternatives include:

1. Material snackbar popup similar to what the ToDo example does.
2. A dedicated notification service such as [Angular2-Toaster](https://www.npmjs.com/package/angular2-toaster)
3. A dedicated Error page (Angular component) that would display an error message and, in dev environment only, error message details.

**Comment by timdeschryver** [comment]
I'm not either 😅 
I would say go for option one, with the material snackbar.
