### ISSUE TITLE
The animation `routeAnimationsElements` looks bad on safari.

### ISSUE THREAD

**Issue by Jeykairis** [tomastrajan/angular-ngrx-material-starter#322]
Just launch the app on safari to reproduce the issue : 
<img width="1280" alt="routeanimationselements_safari" src="https://user-images.githubusercontent.com/10895934/45113113-c293df80-b149-11e8-963d-6c191f00c5c8.png">

**Comment by timdeschryver** [comment]
If you want you can open up a pull request with a fix, what do you think @Jeykairis ?

**Comment by tomastrajan** [comment]
@Jeykairis thank you for the report, similar issue was in IE 11 and EDGE so the animation is disabled if such a browser is detected. We could add Safari too, please have a look at [app.component.ts](https://github.com/tomastrajan/angular-ngrx-material-starter/blob/master/src/app/app.component.ts#L74) it disables page animation for `ie` and `edge`, can you try also with safari?
