### ISSUE TITLE
firebase hosting issues

### ISSUE THREAD

**Issue by taleos** [tomastrajan/angular-ngrx-material-starter#329]
deploying the project to firebase hosting all the menus and the menu bar is disabled because of the multilingual nature of the project. 
example link here: https://testi18n-c3dab.firebaseapp.com
any trick to make it work properly? 
thanks in advance

**Comment by tomastrajan** [comment]
Sure, you have to adjust prod build script which is adjusted to work with GitHub Pages... The current urls look like `https://testi18n-c3dab.firebaseapp.com/angular-ngrx-material-starter/assets/i18n/en.json` but in your case the real url looks more like `https://testi18n-c3dab.firebaseapp.com/assets/i18n/en.json`

You can adjust build script in `package.json` by removing ` -- --deploy-url /angular-ngrx-material-starter/ --base-href /angular-ngrx-material-starter` part and rebuilding the project.

Hope this helps!

**Comment by tomastrajan** [comment]
@taleos please check the previous comment, and also I added bullet point into `README.md` "Make it your own" section which explain this for the new users, thank you very much for  your feedback!
