### ISSUE TITLE
Use @ngrx-router-store

### ISSUE THREAD

**Issue by Jeykairis** [tomastrajan/angular-ngrx-material-starter#331]
It would be great to show how to use @ngrx-router-store.

I'm trying to figure out how to achieve it with the CustomSerializer from the ngrx doc.
The goal could be to get the selected book from the url managing errors.

Do you have other ideas to show advanced use cases or any starting point?

**Comment by timdeschryver** [comment]
Great idea, I'm OK with it. 

I'm not entirely sure what you mean with
> The goal could be to get the selected book from the url managing errors

Also with NgRx 6.1 it isn't needed anymore to provide a serialized, this comes baked in with NgRx itself. If needed are still able to provide a custom serializer tho.

**Comment by Jeykairis** [comment]
After investigation I found https://github.com/ngrx/platform/issues/1262#issuecomment-421066044 and https://github.com/ngrx/platform/commit/e0059bfca6d130061ae6af8f4fa27e97552b60de .

It looks like the doc was updated but the default serializer is not yet available and I don't find the way to connect the custom one. When should it be released?

Otherwise, by managing errors I wanted to say handle the case where the id of the book passed by url is not available in the store through selectors. What else could be done with the router-store?

**Comment by timdeschryver** [comment]
The link you provided, adds more router actions to ngrx-store. 
I was referring to https://github.com/ngrx/platform/commit/389cd78f3517a7ff32930dc1d8187aa7fca712f8 and I thought this would be available in 6.1 but I might be wrong.

> Otherwise, by managing errors I wanted to say handle the case where the id of the book passed by url is not available in the store through selectors. What else could be done with the router-store?

This shouldn't be handled by selectors. A selector is a pure function meaning it should just return an output based on the input. In other words it should to navigate to another page, if this is what you meant.

But we could indeed pluck the book id from the url, and show the selected book.
I briefly touch on this in [NgRx: Parameterized selectors](https://blog.angularindepth.com/ngrx-parameterized-selector-e3f610529f8) and [Sharing data between modules is peanuts.](https://blog.angularindepth.com/sharing-data-between-modules-is-peanuts-3f40fcb38dd) if you need an example. And there was also an excellent talk by Todd Motto and David East during ng-conf [NgRx Selectors How to stop worrying about your Store structure](https://youtu.be/Y4McLi9scfc?t=15m17s)

**Comment by Jeykairis** [comment]
Thank you for the explanations and great articles!
I already saw the video and i'm waitting for ngrx-data! When should it be part of the [ngrx/platform](https://github.com/ngrx/platform) ?

With the 6.1 I got all the router state stored in the state (even if the tag for the default serializer is 6.1...). But I was finally able to register the custom serializer thanks to your commit link.

I open https://github.com/tomastrajan/angular-ngrx-material-starter/pull/355/commits/e96e406f430bb5ccd88879d6e413fea4a0e35d61 with the router state that's  always undefined.

Could you have a look and give me some feedback if you find anything wrong?

**Comment by timdeschryver** [comment]
I'll take a look this week, thanks in advance for the PR!

**Comment by timdeschryver** [comment]
Hey @Jeykairis just wanted to let you know that I haven't taken a look yet, but I haven't forgotten about this. It's just a busy period. I'll get to it this week tho.

**Comment by Jeykairis** [comment]
Hi @timdeschryver, that's all right. Thanks for letting me know.

**Comment by timdeschryver** [comment]
Closed via e66cd8ee8c703f17ac06b66ceff6f8fba8b1018f.
