### ISSUE TITLE
theme not loaded after page refresh in development mode

### ISSUE THREAD

**Issue by enterprisebug** [tomastrajan/angular-ngrx-material-starter#34]
Hi,

after selecting e.g. the LIGHT-THEME on your [published website](https://tomastrajan.github.io/angular-ngrx-material-starter) the theme gets restored when refreshing the page. That is what is expected...

When cloning your rep the theme gets not restored in development mode after refreshing the page with F5. 

I tried debugging for quite a while but couldn't find any solution.
Do you have a fix for that?

Thanks,
Daniel

**Comment by tomastrajan** [comment]
Hmm, interesting. Can you see theme configuration in local storage for lolcalgost when in dev mode? I only remember how to check it in Chrome, the dev tools application tab.

**Comment by tomastrajan** [comment]
I did some testing and it seems to be working in Chrome but not in Firefox and IE. Will look into why later...

**Comment by enterprisebug** [comment]
i have attached a screenshot for Chrome and IE11.

the setting gets stored but on initial load not restored.

even on settings page the stored theme gets not preselected.

i don't know if this is an issue of your repo but i am a fan of it because it shows a lot of great studd.

i tried reading: [Initial State and Ahead of Time (AoT) Compilation](https://github.com/ngrx/platform/blob/master/docs/store/api.md#initial-state-and-ahead-of-time-aot-compilation) but didn't get the clue.

![2018-01-08 05_50_23-settings - angular ngrx material starter](https://user-images.githubusercontent.com/1539741/34659383-8942c936-f438-11e7-86bb-6fc84bf63a47.png)

**Comment by enterprisebug** [comment]
okay. just observed on your [PROD site](https://tomastrajan.github.io/angular-ngrx-material-starter#/about):

It is working if **ANMS-AUTH** key is present.

![application_key](https://user-images.githubusercontent.com/1539741/34660531-56e79c54-f443-11e7-8e4a-ae0cf1aa0156.png)

If you delete this key then it is not working.
That should be an easy fix now. I will check it later.

**Comment by enterprisebug** [comment]
@tomastrajan i thought it would be an easy fix. But actually i don't get it.
Do you have any other clue how to solve this?

**Comment by tomastrajan** [comment]
@enterprisebug yeah it should be related to the way we're initializing ngrx store on app startup, its looking for the keys per reducer / feature and probably this fails if the key (in our case ANMS-AUTH) is not present and probably the exception is swallowed silently. I am currently camping in Tasmania so not much internet or electricity is available but try checking / debugging local storage service in core module. Also, thank you very much for looking into this, I appretiate it a lot!

**Comment by tomastrajan** [comment]
So the problem is in the  [local storage service](https://github.com/tomastrajan/angular-ngrx-material-starter/blob/06a51a573700371ccc95b418cea8045e5b33e6cf/src/app/core/local-storage/local-storage.service.ts#L28). This fails when the key is not found in local storage so we have to skip JSON parse in those cases.

**Comment by enterprisebug** [comment]
I was not able to find any swallowed exceptions... 

Loading the initial state seems to work in my opinion:

    export function getInitialState() {
        const initialState = LocalStorageService.loadInitialState();
        console.log(initialState);
        return initialState;
    }

this loads the setting:
![2018-01-09 15_56_53-about - angular ngrx material starter](https://user-images.githubusercontent.com/1539741/34726998-e2c4fef2-f555-11e7-8c17-da9c65256105.png)

come back to a place where you have internet connection and electricity :-)

**Comment by enterprisebug** [comment]
strange. even after commenting the *selectorAuth*

    ngOnInit(): void {
      this.store
        .select(selectorSettings)
        .pipe(
          takeUntil(this.unsubscribe$),
          map(({ theme }) => theme.toLowerCase())
        )
        .subscribe(theme => {
          console.log(theme); // writes to console: default-theme
          this.componentCssClass = theme;
          this.overlayContainer.getContainerElement().classList.add(theme);
        });
      // this.store
      //   .select(selectorAuth)
      //   .pipe(takeUntil(this.unsubscribe$))
      //   .subscribe(auth => (this.isAuthenticated = auth.isAuthenticated));

**Comment by tomastrajan** [comment]
Can you see theme class applied correctly in HTML like  `<anms-root class="<theme-name>-theme">` ?

**Comment by enterprisebug** [comment]
i am not authenticated.
i have deleted the ANMS-AUTH key from localstorage.
i have chose the BLACK-THEME.
![2018-01-11 05_58_36-microsoft edge](https://user-images.githubusercontent.com/1539741/34809322-87cb59e8-f694-11e7-896b-b27e896bba2f.png)

this is loading the default-theme.
it produced the following HTML when loading the app:
![2018-01-11 06_00_43-einstellungen](https://user-images.githubusercontent.com/1539741/34809354-cefd2832-f694-11e7-9974-728bf7ac9182.png)

yes, it produces the correct HTML if the ANMS-AUTH key is present:
![2018-01-11 06_03_48-aisto_xt debugging - microsoft visual studio](https://user-images.githubusercontent.com/1539741/34809438-3d33d378-f695-11e7-9029-b9f5da9ca980.png)

it it just not loading correct theme if the ANMS-AUTH is **not** present.

**Comment by tomastrajan** [comment]
Ok I found out what the problem was. The initial state was retrieved correctly. Only auth reducer is available during init phase (other 2 are lazy loaded) so when we reduce initial state without `auth` key auth reducer gets triggered and generates new state with its initial state. This new generated state is different from original one so it replaces it effectively throwing away other state keys for reducers which were not yet loaded.

Solution is to load and merge initial state on both `INIT` and `UPDATE` (reducers) actions. `UPDATE` action is triggered when lazy loaded reducer is added to the application.

**Comment by enterprisebug** [comment]
@tomastrajan perfect! I'm really glad you found a solution!
Thanks man! I really appreciate it!
