### ISSUE TITLE
Effects and css not fully loaded when navigating

### ISSUE THREAD

**Issue by Jeebix** [tomastrajan/angular-ngrx-material-starter#347]
Hello,

First thanks for this starter kit which is great, but I have a problem : my static-routing.module is configured like this
const routes: Routes = [
    {
        path: 'tombolas',
        component: HomeComponent
    },
    {
        path: 'tombolas/:id',
        component: TombolaDetailComponent
    },
    {
        path: 'tombolas/draw/:id',
        component: TombolaDrawComponent
    }
];

@NgModule({
    imports: [RouterModule.forChild(routes)],
    exports: [RouterModule]
})

My HomeComponent contains 2 components : FiltersComponent and ListComponent. ListComponent have the link to the TombolaDetailComponent, which is displayed in a mat-table: 
<ng-container matColumnDef="edit">
                <mat-header-cell *matHeaderCellDef></mat-header-cell>
                <mat-cell *matCellDef="let row"><a matTooltip="Edition" [routerLink]="['/tombolas', row.id]" routerLinkActive="active"><i class="fas fa-edit"></i></a>
                </mat-cell>
            </ng-container>

The problem is when navigating to this route (/tombolas/:id), there is no effects and some styles are not loaded, but when refreshing the page, all the styles are in place...

Thanks for your help...

Best, Jean-Baptiste

**Comment by tomastrajan** [comment]
@Jeebix where do you declare `Tombola*Component` in the `declarations:[]` property?

**Comment by Jeebix** [comment]
Here is my static-routing.module : 
`import { NgModule } from '@angular/core';
import { Routes, RouterModule } from '@angular/router';

import { TombolasListComponent } from '@app/static/tombolas-list/tombolas-list.component';
import { TombolaDetailComponent } from '@app/static/tombola-detail/tombola-detail.component';
import { TombolaDrawComponent } from '@app/static/tombola-draw/tombola-draw.component';

const routes: Routes = [
    {
        path: 'tombolas',
        component: TombolasListComponent
    },
    {
        path: 'tombolas/:id',
        component: TombolaDetailComponent
    },
    {
        path: 'tombolas/draw/:id',
        component: TombolaDrawComponent
    }
];

@NgModule({
    imports: [RouterModule.forChild(routes)],
    exports: [RouterModule]
})
export class StaticRoutingModule { }`

Declarations are in the static.module : 
`import { NgModule } from '@angular/core';

import { SharedModule } from '@app/shared';

import { StaticRoutingModule } from './static-routing.module';
import { TombolasListComponent } from './tombolas-list/tombolas-list.component';
import { TombolasFiltersComponent } from './tombolas-filters/tombolas-filters.component';
import { TombolaDetailComponent } from './tombola-detail/tombola-detail.component';
import { TombolaPrizesComponent } from './tombola-prizes/tombola-prizes.component';
import { TombolaDrawComponent } from './tombola-draw/tombola-draw.component';
import { ModalTombolasPrintComponent } from './modal-tombolas-print/modal-tombolas-print.component';
import { ModalTombolasDeletePrintComponent } from './modal-tombolas-delete-print/modal-tombolas-delete-print.component';
import { ModalDeletePrizesComponent } from './modal-delete-prizes/modal-delete-prizes.component';

@NgModule({
    imports: [SharedModule, StaticRoutingModule],
    declarations:
    [
        TombolasListComponent,
        TombolasFiltersComponent,
        TombolaDetailComponent,
        TombolaPrizesComponent,
        TombolaDrawComponent,
        ModalTombolasPrintComponent,
        ModalTombolasDeletePrintComponent,
        ModalDeletePrizesComponent
    ],
    entryComponents: [
        ModalTombolasPrintComponent,
        ModalTombolasDeletePrintComponent,
        ModalDeletePrizesComponent
    ]
})
export class StaticModule { }`

When I navigate to the TombolaDetailComponent, the styles are loaded but not fully applied on material elements, and when I refresh all is OK... When I go back to the entry component (TombolaListComponent), the transition is OK and the material styles are correctly applied.

Best

**Comment by tomastrajan** [comment]
Project went through major update to Angular 8, please open new issue if the behavior persists. ( Old issue cleanup)
