### ISSUE TITLE
Memory leak!!!

### ISSUE THREAD

**Issue by timdeschryver** [tomastrajan/angular-ngrx-material-starter#349]
Currently there is a memory leak inside the CRUD component.
Because memory leaks aren't really our thing, we would prefer not to have one.

You can watch Kwinten's talk [Keep your memor(ies|y) safe!](https://www.youtube.com/watch?v=OOF2WIFTMaI) from NgTalks 2018 to learn how to track memory leaks and how to solve them.

Leave a comment if you would like to take this issue.

**Comment by simply10w** [comment]
I created a PR here:
