### ISSUE TITLE
<mat-sidenav-container> is not a known element

### ISSUE THREAD

**Issue by RonaldBastien** [tomastrajan/angular-ngrx-material-starter#35]
I get an error 'mat-sidenav-container' is not a know element in app.component.html 

When I click on the icon in the <mat-toolbar> the (click)="sidenav.open()" does not trigger.

I've tried the online demo 
https://tomastrajan.github.io/angular-ngrx-material-starter#/about 
in both Chrome and Edge  and get the same behaviour (I don't get the sidenav bar)

Any idea what would be the problem?

**Comment by tomastrajan** [comment]
Hi! Thank you for finding the issue. This could be caused by changes in API of angular.material sidenav component with newer versions of angular material, will look into it when I am back in civilization around end of january... Feel free to check it out and submit PR too 😉

**Comment by tomastrajan** [comment]
Hmm strange, I just tried both  DEV and PROD mode (on GitHub pages) in Chrome and Edge and side menu works in both cases. I can navigate to available routes and console doesn't show any error so could you please provide more details?

**Comment by RonaldBastien** [comment]
I figured out that the button that enables the sidenav.open() is hidden with a class attribute in app.component.html

<button mat-icon-button class="**hidden-md-up**" (click)="sidenav.open()">

If I remove the "hidden-md-up" class, then I see the menu icon, and clicking on it opens up the sidenav.  

What I don't understand is why that is hidden at start up and how does a user get it to display.  I must be missing something as a user when I run the demo app.

**Comment by tomastrajan** [comment]
Ok so the `hidden-md-up` is a bootstrap css class which serves as a responsive utility and hides element on every display which is at least medium size or bigger. Application has normal top menu with all items by default. Menu is collapsed on smaller screens and replaced by the hamburger menu which slides out on click. 

It seems that this works as expected, does it answer your question?

**Comment by RonaldBastien** [comment]
Yes it does.  Totally.  I truly feel like a newbie.

Thanks for taking the time to write back.

**Comment by tomastrajan** [comment]
No worries, cheers mate! 🎉

**Comment by Anasteisha1love** [comment]
=*мпрарсрпаррпрапврапааапмп
