### ISSUE TITLE
compile failed with docker

### ISSUE THREAD

**Issue by capaneus** [tomastrajan/angular-ngrx-material-starter#359]
Hi,
I'm trying to put starter in the docker env recently, but there is very strange compile issue:
`ERROR in src/app/examples/examples/examples.component.ts(57,13): error TS2345: Argument of type '(source$: Observable<State>) => Observable<SettingsState>' is not assignable to parameter of
type 'OperatorFunction<State, SettingsState>'.
  Types of parameters 'source$' and 'source' are incompatible.
    Type 'import("/usr/src/app/node_modules/rxjs/internal/Observable").Observable<import("/usr/src/app/src/...' is not assignable to type 'import("/usr/src/app/node_modules/rxjs/internal/Observable").Observable<import("/usr/src/app/src/...'. Two different types with this name exist, but they are unrelated.
      Type 'import("/usr/src/app/src/app/examples/examples.state").State' is not assignable to type 'import("/usr/src/app/src/app/settings/settings.model").State'.
        Property 'settings' is missing in type 'State'.`

I'm following this tutorial here: https://mherman.org/blog/dockerizing-an-angular-app/ 
and modified a bit Dockerfile to install cypress. Below is my Dockerfile:
`# base image
FROM node:9.6.1

# install chrome for protractor tests
RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
RUN sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
RUN apt-get update && apt-get install -yq google-chrome-stable

# set working directory
RUN mkdir /usr/src/app
RUN mkdir /usr/src/app/cypress
RUN mkdir /usr/src/app/cypress/plugins
WORKDIR /usr/src/app

# add `/usr/src/app/node_modules/.bin` to $PATH
ENV PATH /usr/src/app/node_modules/.bin:$PATH

# install and cache app dependencies
COPY package.json /usr/src/app/package.json
RUN npm install
RUN npm install -g @angular/cli@1.7.1

# add app
COPY . /usr/src/app

EXPOSE 4200

# start app
CMD ng serve --host 0.0.0.0
`

Can anyone help?

Thanks a lot!

**Comment by capaneus** [comment]
I failed with this step: docker run -it -v /usr/src/app -v /usr/src/app/node_modules -p 4200:4200 --rm myclient

**Comment by capaneus** [comment]
Hi @tomastrajan 
Thanks for the super quick feedback, I tried to remove this line
RUN npm install -g @angular/cli@1.7.1

and rebuilt the image, but seems the crash is still there...
all I did is cloned angular-ngrx-material-starter and added docker files.

**Comment by tomastrajan** [comment]
@capaneus does it work for you locally without docker ?

**Comment by capaneus** [comment]
@tomastrajan yes, I compiled with ng serve and production build, both works fine, so it's super strange. my system is windows 10, but that shouldn't affect it...

**Comment by tomastrajan** [comment]
@capaneus checking the error message, somehow in the docker you get two copies / versions of the `rxjs` stuff which is clashing, hard to say why. Does something exits in the environment already, is the install process duplicating something, hard to say, but that's the hint.

**Comment by harm-less** [comment]
It happens to me as well even without compiling. I'm going to try to look into the problem now.

![image](https://user-images.githubusercontent.com/6368074/46469866-fad41f80-c7d4-11e8-8ace-cb64277e7966.png)
