### ISSUE TITLE
Add Cypress tests for Stocks

### ISSUE THREAD

**Issue by timdeschryver** [tomastrajan/angular-ngrx-material-starter#372]
Add Cypress tests for the [Stocks example](https://tomastrajan.github.io/angular-ngrx-material-starter#/examples/stock-market).

Leave a comment if you would like to take this issue.

**Comment by VitorBarbosa** [comment]
I can take this one 😃

**Comment by tomastrajan** [comment]
@VitorBarbosa go for it :)

**Comment by timdeschryver** [comment]
Hi @VitorBarbosa, just checking if everything is alright or if you need some help.

**Comment by VitorBarbosa** [comment]
Hi @timdeschryver , thanks :)
Sorry for the delay, just today I'm getting started on this.
I'll respond if I get stuck on anything.
