### ISSUE TITLE
Add Cypress tests for CRUD

### ISSUE THREAD

**Issue by timdeschryver** [tomastrajan/angular-ngrx-material-starter#373]
Add Cypress tests for the [CRUD example](https://tomastrajan.github.io/angular-ngrx-material-starter#/examples/crud).

Leave a comment if you would like to take this issue.

**Comment by vishalsodani** [comment]
I would like to work on this.

**Comment by timdeschryver** [comment]
Go for it @vishalsodani , thanks!
