### ISSUE TITLE
Implement Notification Service

### ISSUE THREAD

**Issue by hhubik** [tomastrajan/angular-ngrx-material-starter#377]
Service to provide UI notifications of the following types:
* info
* warn
* error

Per @tomastrajan  suggestion https://github.com/tomastrajan/angular-ngrx-material-starter/pull/360#discussion_r221825600

Should be done after #321 is closed.

**Comment by tomastrajan** [comment]
@hhubik thank you for creating this! 
Extra info: should be created in `CoreModule`.

**Comment by hhubik** [comment]
I'll do this one now.
