### ISSUE TITLE
Making the project accessible 

### ISSUE THREAD

**Issue by timdeschryver** [tomastrajan/angular-ngrx-material-starter#388]
## Describe the feature you'd like:
We added [pa11y](https://github.com/pa11y/pa11y) to run accessibility checks on the website (https://github.com/tomastrajan/angular-ngrx-material-starter/commit/af32ac5046e812d7ca1338d16b7a20a35336ab04).
To run these checks, use `npm run accessibility` and you'll see a overview of the errors.

![1_urdmmj38kb8haujy4zwiaq](https://user-images.githubusercontent.com/28659384/46691080-4850f200-cc04-11e8-9d19-55d1b47d3558.png)

It would be nice to have these issues solved.
For more info see [Test for accessibility and help millions of people](https://blog.angularindepth.com/test-for-accessibility-and-help-millions-of-people-97d86f72e2c4)

The pages that we have to make fully accessible are the following (the urls to check are defined in `.pa11yci`):

- [ ] Home
- [ ] Features
- [ ] Examples/todos
- [ ] Examples/stock-market
- [ ] Examples/theming
- [ ] Examples/crud
- [ ] Examples/form

If you want to take a page for your count, leave a comment below.

**Comment by geromegrignon** [comment]
As the issues are mainly in the app.component, i take them all.

**Comment by tomastrajan** [comment]
@geromegrignon very appreciated!

**Comment by tomastrajan** [comment]
Was fixed
