### ISSUE TITLE
Animations in Safari seam to flicker

### ISSUE THREAD

**Issue by nblopes** [tomastrajan/angular-ngrx-material-starter#39]
Been testing this in multiple browsers including Safari, Edge and IE11.

Safari:
The animations in Safari seam to flicker.

Edge: The animations in Edge seam to flicker.

IE11:
As it is does not run. IE11 does not support "includes" method in Strings. As a result its crashes. Use "indexOf" instead.

**Comment by tomastrajan** [comment]
Thank you very much for your effort will definitelly look into it. For IE11 the solution will be to import core-js polyfill to support includes.

**Comment by tomastrajan** [comment]
Still the animation fickleness is worth looking into.
