### ISSUE TITLE
Stop a redirect to the default route on error

### ISSUE THREAD

**Issue by harm-less** [tomastrajan/angular-ngrx-material-starter#398]
## Minimal reproduction of the bug with instructions:
Make a critical error on a route you're visiting. For example by not importing a component you're using.

## Expected behavior:
I want to it stay on the same page/route without redirecting back to http://localhost:4200/ or http://localhost:4200/about. It doesn't do this on every error, but even when you are already on a specific page and make a fatal error I expect it it to report the error and stay on that page.
At least while developing this is a very annoying behavior.

## Other information:
I tried searching the code and `angular-cli` in general, but nothing I could find about this topic. I'm hoping I missed a small detail somewhere.

**Comment by tomastrajan** [comment]
@harm-less does this only hapen on lazy routes or ? I am not aware of any specific code in our Exception handler which would lead to such a behaviour...

**Comment by tomastrajan** [comment]
Project went through major update to Angular 8, please open new issue if the behavior persists. ( Old issue cleanup)
