### ISSUE TITLE
Really Cool

### ISSUE THREAD

**Issue by kludgeDan** [tomastrajan/angular-ngrx-material-starter#4]
Not really an issue but I didn't see any licensing on the main page. I was assuming this is MIT but wasn't sure. Really like the big input component. Wanted to use it in a site I am making. Been reading your blog and watching your videos as well and just wanted to say thanks for teaching me Material!

**Comment by tomastrajan** [comment]
Happy to hear you find this repo helpful. I added the MIT license file enjoy!
