### ISSUE TITLE
Double scrollbar on page transition in long pages (regression)

### ISSUE THREAD

**Issue by tomastrajan** [tomastrajan/angular-ngrx-material-starter#400]
## Minimal reproduction of the bug with instructions:
Navigate to page with long content like features or about shows secondary inner scrollbar

## Expected behavior:
Single outer scrollbar

![anms-issue](https://user-images.githubusercontent.com/3764868/47185436-ab8e0300-d32d-11e8-8587-e9faafd739d4.png)

**Comment by GrzegorzStanczyk** [comment]
I have quick fix. I can make PR.
