### ISSUE TITLE
karma-coverage-istanbul-reporter doesnot show any data for code coverage

### ISSUE THREAD

**Issue by Sharique-Hasan** [tomastrajan/angular-ngrx-material-starter#405]
## Minimal reproduction of the bug with instructions:
Clone the repo and run the tests.

## Current behavior:

``` 
*Coverage summary* 
Statements   : Unknown% ( 0/0 )
Branches     : Unknown% ( 0/0 )
Functions    : Unknown% ( 0/0 )
Lines        : Unknown% ( 0/0 )
```
Running `ng test --code-coverage` gives out this error: 

```
WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.module.rules[14].include: The provided value "\\src" is not an absolute path!
```

## Expected behavior:
Coverage summary should show proper coverage of code.

## I would be willing to submit a PR to fix this issue:

[x] Yes (Assistance is provided if you need help submitting a pull request)  
[ ] No

**Comment by tomastrajan** [comment]
Yes, this was added recently and doesn't really work, I suppose some version mismatch between CLi, karma and reporter, would you be interested in having a look into this ?

**Comment by tomastrajan** [comment]
Was fixed by this [commit](https://github.com/tomastrajan/angular-ngrx-material-starter/commit/a03983933f237c39b9e031db2bd851cb8a6f1bd5)
