### ISSUE TITLE
Constant stream of network requests for google analytics and Cypress tests hang and/or type super slow

### ISSUE THREAD

**Issue by chauey** [tomastrajan/angular-ngrx-material-starter#417]
## Minimal reproduction of the bug with instructions:
Run the app
`npm start`

Run the cypress tests
`npm run cy:open`
run any test

## Expected behavior:
No constant stream of network requests. 
No hanging tests.
Cypress typing into the inputs is not slow (after 5 minutes, has only typed "The Lit" of "The Little Schemer")

## Other information:
Did something change in the code? Or need to configure dev environment? Or the google analytics account/key is no longer valid? I had problems on 2 different machines, the cypress tests used to work better not too long ago. If I comment out the "ga(" stuff in 2 files, it works better. I tried reverting to Cypress 3.1.0 but had mixed results.

## I would be willing to submit a PR to fix this issue:

[ x ] Yes (Assistance is provided if you need help submitting a pull request)  
[ ] No

**Comment by timdeschryver** [comment]
I've also noticed this during development today.
I'm expecting this to be the cause of the failing e2e tests with protractor.

**Comment by timdeschryver** [comment]
Hi @chauey, it should be resolved when you pull the latest changes.
Feel free to re-open if this doesn't fix it.
