### ISSUE TITLE
Write tests for untested reducers, actions and effects

### ISSUE THREAD

**Issue by timdeschryver** [tomastrajan/angular-ngrx-material-starter#419]
I refactored some parts in https://github.com/tomastrajan/angular-ngrx-material-starter/pull/418 but forgot to write tests 😅 .
If someone wants to pick this one up feel free to do so, but leave a comment down below.
If no one picks this up during the next weeks, I will create them.

## I would be willing to submit a PR to fix this issue:

[x] Yes (Assistance is provided if you need help submitting a pull request)  
[ ] No

**Comment by lau32** [comment]
I can take this up.

**Comment by timdeschryver** [comment]
That's great to hear @lau32, thanks!
