### ISSUE TITLE
prettier does not go deep in folders using "format" scripts

### ISSUE THREAD

**Issue by akalitenya** [tomastrajan/angular-ngrx-material-starter#427]
```yarn "format:write"``` and ```yarn "format:test"``` does not go deep (recursive) on folders
## Expected behavior:
files should be formatted in folders recursively
## Other information:

solution:
```"format:write": "prettier {src,e2e}/**/*.{ts,json,md,scss} --write",``` 

should be rewrited with double quotes

```"format:write": "prettier \"{src,e2e}/**/*.{ts,json,md,scss}\" --write"```

## I would be willing to submit a PR to fix this issue:

[ ] Yes (Assistance is provided if you need help submitting a pull request)  
[* ] No

**Comment by tomastrajan** [comment]
@akalitenya thank you for submitting the issue, I guess it is environment specific as I didn't encounter this problem locally or on Travis CI but we should anyway fix it so that it works for all the users!

**Comment by tomastrajan** [comment]
Hope you found solution for your issue, this might be outdated as project went through major Angular 8 update. (Old issue cleanup)
