### ISSUE TITLE
Module installation didnt exist after install another module

### ISSUE THREAD

**Issue by DianPermana** [tomastrajan/angular-ngrx-material-starter#439]
Hello, I have tried to install firebase module (https://github.com/angular/angularfire2), and it worked then I closed my application, the firebase module still exists. a problem began to appear when I installed another module, for example I have tried to install the chart.js module (https://github.com/chartjs/Chart.js), and it worked. But the firebase module that didn't exist before (disappeared).

**Comment by DianPermana** [comment]
so, I found a bug that this angular-ngrx-material-starter couldn't add (install) another module (just one module).

For example when we installed the chart.js module, then installed angularfire (Firebase) module 

Result  : only one module is installed, (only the last one is installed)
Expected : The chart.js module and angularfire module should be exist because I install module chartjs and module angularfire (Firebase).

why did this happen?

**Comment by tomastrajan** [comment]
Project went through major update to Angular 8, please open new issue if the behavior persists. ( Old issue cleanup)
