### ISSUE TITLE
Minor typing error

### ISSUE THREAD

**Issue by turbod89** [tomastrajan/angular-ngrx-material-starter#442]
## Minimal reproduction of the bug with instructions:

On file src/app/settings/settings.effects.ts, line 52, there is
```
  changeHour = interval(60_000).pipe(
```

##Expected behavior:

I think it should be:
```
  changeHour = interval(60000).pipe(
```

## I would be willing to submit a PR to fix this issue:

[ ] Yes (Assistance is provided if you need help submitting a pull request)  
[X] No

**Comment by timdeschryver** [comment]
Hi thanks for opening this issue @turbod89 !
The syntax `60_000` is called a numeric separator, "TypeScript 2.7 brings support for ES Numeric Separators. Numeric literals can now be separated into segments using _." - see https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-7.html for more info. 

In short it's make it easier to read, imho.
