### ISSUE TITLE
Upgrade to NgRx 7 and use MockStore

### ISSUE THREAD

**Issue by timdeschryver** [tomastrajan/angular-ngrx-material-starter#444]
With the release of NgRx 7, it also introduces a `MockStore`.
I think we should update to NgRx 7 and replace our implementation of `MockStore` with the NgRx 7 `MockStore` store.
The lesser part is that this isn't documented yet, but its signature looks a lot like ours!

For more info, take a look at the PR that introduced `MockStore` - https://github.com/ngrx/platform/pull/1027.

**Comment by lau32** [comment]
I could take this up.

**Comment by tomastrajan** [comment]
Please that would be amazing !

**Comment by tomastrajan** [comment]
This was solved by the Angular 8 migration.
