### ISSUE TITLE
Typescript : use namespace as type in typescript

### ISSUE THREAD

**Issue by rjain15** [tomastrajan/angular-ngrx-material-starter#445]
Not sure if this is based on the typescript version I have, I was getting an error 
"Cannot use namespace as a type" in the the constructor of app.component.ts

I changed this based on this stackoverflow suggestion
https://stackoverflow.com/questions/42815932/use-namespace-as-type-in-typescript
and I got it working

```
  constructor(
    private store: Store<typeof AppState>,
    private storageService: typeof LocalStorageService
  ) {}

```

**Comment by tomastrajan** [comment]
Project went through major update to Angular 8, please open new issue if the behavior persists. ( Old issue cleanup)
