### ISSUE TITLE
Livereload not working

### ISSUE THREAD

**Issue by muhammedMoussa** [tomastrajan/angular-ngrx-material-starter#446]
After clone: 
```
yarn install
yarn start
```
making changes there is no listing even if i reload the browser, only when close the server and run it again.
then clone another one:
```
npm install
npm start
```
tried:
```
ng s 
ng s --live-reload
```
but also not working.

> node: 8.15.0
> npm: 6.4.1
> angular-cli: 7.2.2
> linux mint 19

**Comment by shootermv** [comment]
I think it will be better to have some description here: like - what command are you running when you expect livereload to work?  Thanks

**Comment by muhammedMoussa** [comment]
updated

**Comment by shootermv** [comment]
How about run "ng serve"?

**Comment by muhammedMoussa** [comment]
"ng s" is short hand for "ng serve"

**Comment by tomastrajan** [comment]
Project went through major update to Angular 8, please open new issue if the behavior persists. ( Old issue cleanup)
