### ISSUE TITLE
Testing with apollo angular

### ISSUE THREAD

**Issue by anthowm** [tomastrajan/angular-ngrx-material-starter#454]
I have integrated apollo angular with this project but I have a problem with the testing maybe someone of you can answer it. Sorry for make an issue but I need help. 
https://stackoverflow.com/questions/54556471/testing-angular-effect-graphql-apollo-client

**Comment by tomastrajan** [comment]
@anthowm I see your point but this has literally nothing to do with this repo at all. Wish you good luck and feel free to ping us when you have a solution we can add a link for other users who want to use this together with Apollo.
