### ISSUE TITLE
i18 label is missing

### ISSUE THREAD

**Issue by anthowm** [tomastrajan/angular-ngrx-material-starter#459]
## Minimal reproduction of the bug with instructions:
A i18 label is missing "anms.settings.general.language.he" you can check it in settings section.
![image](https://user-images.githubusercontent.com/5764698/53518345-21229080-3ad1-11e9-8d1f-1ce37425d07d.png)

## Expected behavior:
Exist the i18 label

## I would be willing to submit a PR to fix this issue:

[ ] Yes (Assistance is provided if you need help submitting a pull request)  
[ X ] No

**Comment by tomastrajan** [comment]
Fixed #460
