### ISSUE TITLE
App Fails to Start with Schema Validation failure

### ISSUE THREAD

**Issue by selwyntheo** [tomastrajan/angular-ngrx-material-starter#466]
After npm install and npm run causes the following error
> Schema validation failed with the following errors:
>   Data path ".builders['app-shell']" should have required property 'class'.
> Error: Schema validation failed with the following errors:
>   Data path ".builders['app-shell']" should have required property 'class'.
>     at MergeMapSubscriber._registry.compile.pipe.operators_1.concatMap.validatorResult [as project

**Comment by Wigent** [comment]
I get this after doing 'npm audit fix' as 'npm install' finds vulnerabilities. But not doing the audit fix it runs fine.

**Comment by Wigent** [comment]
One way to fix this is to edit package.json and change the line to:
"@angular-devkit/build-angular": "^0.13.4"

**Comment by tomastrajan** [comment]
I am working on update to Angular v8 so there are lot's of fixes coming !

**Comment by tomastrajan** [comment]
Angular 8 migration was released so this is outdated, please open new issue if the behavior persists! (Old issue cleanup)
