### ISSUE TITLE
websocket-driver version 0.7.2 has been deleted, breaking npm install process

### ISSUE THREAD

**Issue by craigchandler** [tomastrajan/angular-ngrx-material-starter#471]
## Minimal reproduction of the bug with instructions:
websocket-driver version 0.7.2 has been deleted, the current package setup will not install
I manually edited package-lock.json to get it going, i'm sure there is a better way

## Expected behavior:
npm install should run cleanly

## Other information:

Here's the edit i made to package-lock.json

"websocket-driver": {
      "version": "0.7.3",
      "resolved": "https://registry.npmjs.org/websocket-driver/-/websocket-driver-0.7.3.tgz",
      "integrity": "sha512-bpxWlvbbB459Mlipc5GBzzZwhoZgGEZLuqPaR0INBGnPAY1vdBX6hPnoFXiw+3yWxDuHyQjO2oXTMyS8A5haFg==",
      "dev": true,
      "requires": {
        "http-parser-js": ">= 0.4.0, < 0.4.11",
        "safe-buffer": ">= 5.1.0",
        "websocket-extensions": ">= 0.1.1"
      }
    },

## I would be willing to submit a PR to fix this issue:

[ ] Yes (Assistance is provided if you need help submitting a pull request)  
[ ] No

**Comment by IssaGithub** [comment]
Habe the same problem :-)

**Comment by mingoal** [comment]
delete `package-lock.json` then `npm install` works for me
