### ISSUE TITLE
Use the NgRx 8 `create` factory functions

### ISSUE THREAD

**Issue by timdeschryver** [tomastrajan/angular-ngrx-material-starter#472]
## Describe the feature you'd like:

The [release of NgRx 8](https://medium.com/ngrx/announcing-ngrx-version-8-ngrx-data-create-functions-runtime-checks-and-mock-selectors-a44fac112627) gave us a way to define actions and reducers in a less verbose way with `createAction` and `createReducer`. I would like to see this project to use these functions and the new `createEffect`.

## Other information:

I tried to list all of the features using NgRx here below. 
Feel free to claim your own feature 🙂

- [x] Auth
- [x] Settings
- [x] CRUD (Books)
- [x] Form
- [x] Stock market
- [x] Todos
- [x] google-analytics

We're here to guide you along the way.
(I will probably pick one feature in a couple of days, to get this started)

**Comment by tomastrajan** [comment]
Also, here is a great blog post detailing how to do it in practice ! https://offering.solutions/blog/articles/2019/07/01/updating-your-angular-app-to-ngrx-8/

**Comment by geromegrignon** [comment]
I'll work on CRUD part tonight.

**Comment by tomastrajan** [comment]
@geromegrigon great, thanks ! 🔥

**Comment by timdeschryver** [comment]
@evgenyfedorenko do you want to pick one up? Please don't feel obligated

**Comment by evgenyfedorenko** [comment]
@timdeschryver a bit slammed at the moment with other stuff. I will certainly consider doing it later.

**Comment by timdeschryver** [comment]
Sure, feel free to check in at any point 🙂

**Comment by santoshyadav198613** [comment]
Hi @timdeschryver ,
I can take few, let me know which part i can work on.

**Comment by timdeschryver** [comment]
I was just about to pick up `Auth` myself, feel free to claim your own @santoshyadav198613

**Comment by santoshyadav198613** [comment]
Cool @timdeschryver , working on one very old issue, as soon as it is done, will pickup Todos.

**Comment by santoshyadav198613** [comment]
I am taking Form next.

**Comment by tomastrajan** [comment]
@timdeschryver  this is coming together in a very nice speed ! Amazing community work!

**Comment by geromegrignon** [comment]
@abedzantout thanks for your contribution but for furthers contributions you should communicate about your contribution to avoid people working both on the same part.
@santoshyadav198613 : Form part has been merged fyi.

**Comment by santoshyadav198613** [comment]
Cool @geromegrignon , in that case taking settings.

**Comment by abedzantout** [comment]
@geronegrignon i’ll Be working on updating the settings also. Should be done soon

**Comment by santoshyadav198613** [comment]
> @geromegrignon i’ll Be working on updating the settings also. Should be done soon.
> 
> @santoshyadav want to help me with the tests ?

Oops i was already done with actions and effects, never mind please update before you start working to avoid rework. 

Sure push the changes i will take care of test cases.

**Comment by abedzantout** [comment]
@santoshyadav198613 Please check PR

**Comment by timdeschryver** [comment]
It seems like we have everything covered, thanks for your help! 🙌

**Comment by tomastrajan** [comment]
Thanks for the epic contributions peeps ! 👍
