### ISSUE TITLE
Cypress no longer supported?

### ISSUE THREAD

**Issue by harm-less** [tomastrajan/angular-ngrx-material-starter#476]
It's not really a bug nor a feature, but I was wondering why Cypress is no longer part of the project as it's not stated in the changelog or any other place I could find?
My main suspicion is that `ng e2e` is the native Angular test method, is that correct?

**Comment by tomastrajan** [comment]
Hi @harm-less ! Yes, I removed cypress as a part of big refactoring and move to Angular 8. The reason for that was that over the years project accumulated quite a lot of bloat which kinda defeats the purpose of being starter which should be easy to navigate and understand.

Compared to that native `ng e2e` and protractor is part of every project generated by Angular CLI out of the box so we can assume that more people know it and have experience writing such tests!

Then again everyone is more than welcome to customize starter as they like for their own use case and in line with their preferences! 😉
