### ISSUE TITLE
How can i make my own project without breaking new updates

### ISSUE THREAD

**Issue by mzane42** [tomastrajan/angular-ngrx-material-starter#479]
Hi, 
First of all thanks for this boilerplate, i found it very helpful to start robust new project in Angular, i have a few questions for you guys in good practices using boilerplate:
- Is it good way to migrate the angular-ngrx-material-starter sources to a root directory and delete the projects directory
- How can i benefit the new updates and continue on my own project at the same time

**Comment by tomastrajan** [comment]
@mzane42 thanks for kind words! 

Subjectively I am in favor of `projects/` dir as Angular CLI supports multiple projects in a monorepo style and you can have stuff like server / utils / shared lib / whatever... The const for it is not too much ( a bit longer path ).

Then again, it is possible to move everything to `/src` but you will have to adjust some paths in `package.json` and `angular.json`...


As for updates... That depends, if you change your project structure that can be hard, if not it should be possible to merge this starter into your project while handling conflicts manually. Or, just keep an eye on commit log of this repo and use changes that are interesting for you...

Anyway it is ok to use repo as is at any point of time it should work and be pretty consistent, then as you build your own stuff you will evolve it based on your needs :)

Hope this answered your question :)

**Comment by mzane42** [comment]
@tomastrajan Thanks for your fast and useful answer !
Wish to contribute soon in this project :)
