### ISSUE TITLE
Problem with adding fontawesome icons

### ISSUE THREAD

**Issue by aoighost** [tomastrajan/angular-ngrx-material-starter#488]
I know this is probably my fault but I need to ask anyway. I'm trying to add a button, "cases" to the dropdown where logout goes when authed. I try to add an icon but while the space is placed for it, no icon, in this case the fontawesome folder icon, shows up. Does anyone have any info on why this is happening and how to fix it?

`
            <button mat-menu-item (click)="onLogoutClick()">
              <mat-icon><fa-icon icon="folder"></fa-icon></mat-icon>
              <span>{{ 'navrie-frontend.menu.cases' | translate }}</span>
            </button>`

**Comment by tomastrajan** [comment]
Hi @aoighost !

Did you also add your icon into [here](https://github.com/tomastrajan/angular-ngrx-material-starter/blob/master/projects/angular-ngrx-material-starter/src/app/shared/shared.module.ts) ?

**Comment by aoighost** [comment]
No I didn't, thanks for pointing that out.
