### ISSUE TITLE
What's the difference between static folder and the examples folder? 

### ISSUE THREAD

**Issue by elucidsoft** [tomastrajan/angular-ngrx-material-starter#50]
I don't get the distinction between these two folders?  Can you elaborate on this a bit?

**Comment by tomastrajan** [comment]
Hi @elucidsoft !

The difference is that `static` is ment to be used for static (marketing) content with static pages which just display info without much functionality. In our case it's `about` and `features` pages. But in Angular terms its a `feature module`. Just a way to organize code.

Examples is a lazy loaded feature module with app like functionality. Again its more about code organization. 

In your app you will have different feature modules based on your needs.
