### ISSUE TITLE
window.scrollTo not working

### ISSUE THREAD

**Issue by hieuntp2** [tomastrajan/angular-ngrx-material-starter#502]
## Minimal reproduction of the bug with instructions:
As normal, when we call `window.scrollTop(0,0)`, browser will scroll to top. Or for simple, when scroll bottom of page, open console and call  `window.scrollTop(0,0)`, current page will scroll to top.

## Expected behavior:
Browser will scroll to expected location.

## I would be willing to submit a PR to fix this issue:

[ ] Yes (Assistance is provided if you need help submitting a pull request)  
[x ] No

**Comment by tomastrajan** [comment]
Hi @hieuntp2 !

This is a browser API, not Angular itself... Which browser did you try ? Also try to remove router config object with scroll behavior and try again ? 

https://github.com/tomastrajan/angular-ngrx-material-starter/blob/master/projects/angular-ngrx-material-starter/src/app/app-routing.module.ts#L43

**Comment by varunahuja555** [comment]
@hieuntp2 
Try this. It's working
`const elmnt = document.getElementById(id);
    elmnt.scrollIntoView({behavior: 'smooth'});`
