### ISSUE TITLE
Cleanup: css class default-notification-overlay was not created

### ISSUE THREAD

**Issue by gmaresca** [tomastrajan/angular-ngrx-material-starter#507]
### This is just a cleanup item.

It doesn't look like this class was created to style default notifications even if it is referenced in notification.service.ts panelClass

```
default(message: string) {
    this.show(message, {
      duration: 2000,
      panelClass: 'default-notification-overlay'
    });
  }
```

**Comment by tomastrajan** [comment]
Hi @gmaresca !

If I remember correctly this was added for consistency reasons even though it might not have been needed for actual styling...

Hope that helps!

**Comment by gmaresca** [comment]
OK
