### ISSUE TITLE
Compiling the code for production

### ISSUE THREAD

**Issue by joslash** [tomastrajan/angular-ngrx-material-starter#509]
Hi there! I need to release my project, so I compiled it 
`ng build --prod`

But when I copy all files inside dist folder to an http server, it can't load the app unless I comple the project like
`ng build --prod --base-href sistema-institucional`

Then everything works fine, but the url is like 
`<server>/sistema-institucional/sistema-institucional#/`

I would rather a url like
`<server>/sistema-institucional#/`
but if I compile it without  --base-href it doesn't load.

**Comment by tomastrajan** [comment]
Hi @joslash !

CHeck out `build` npm scripts in `package.json` file, how they are done, you may need to adjust base-href and output url in multiple  places, by default Angular apps are build for serving from root `/` but I had to change it in the starter to work on github which needs specific context path based on the project name

Good luck :)

**Comment by joslash** [comment]
Ok, thank you!
