### ISSUE TITLE
Enable strict mode

### ISSUE THREAD

**Issue by daboudii** [tomastrajan/angular-ngrx-material-starter#536]
After reading this [Angular blog post](https://blog.angular.io/angular-cli-strict-mode-c94ba5965f63), I thought it would be nice to make your starter app  in strict mode.

#  Describe the feature you'd like:

Enable stricter type checking in tsconfig.json: 
-    strictPropertyInitialization
-    strictNullChecks
-    noImplicitAny
-    strictBindCallApply
-    strictFunctionTypes

Reduce Bundle Budgets:
- 500KB warning and 1MB error budget for the initial JavaScript we send to the browser
- 2KB warning and 4KB error budget for the styles of any component 

## Other information:
`"strictBindCallApply": true,`  do not cause compilation errors.
the rest of them does fail compilation.

## I would be willing to submit a PR to fix this issue:

[] Yes (Assistance is provided if you need help submitting a pull request)  
[x] No

**Comment by tomastrajan** [comment]
@daboudii sounds like good idea, would be nice to get an PR ;)

**Comment by jthoms** [comment]
+1 to merge the PR

**Comment by tomastrajan** [comment]
Would love to but...

![image](https://user-images.githubusercontent.com/3764868/124148050-93d01c00-da8f-11eb-8e40-4cefdcd8f804.png)

**Comment by slegge** [comment]
I have merged the latest and resolved all conflicts

**Comment by tomastrajan** [comment]
@slegge thank you for your contribution!
