### ISSUE TITLE
Help please !

### ISSUE THREAD

**Issue by Danubius1st** [tomastrajan/angular-ngrx-material-starter#540]
I have an error trying to rewrite the app. Any hint would be appreciated.

**app.component.ts:**
![01  app component ts](https://user-images.githubusercontent.com/22094979/94840238-cb3a6b00-0420-11eb-82b0-0aea96e427b4.png)

![02  app component ts](https://user-images.githubusercontent.com/22094979/94840248-cecdf200-0420-11eb-9dff-ae0245b97560.png)

**app.module.ts:**
![03  app module ts](https://user-images.githubusercontent.com/22094979/94840255-d1c8e280-0420-11eb-8827-4ffd8b078de8.png)

**core.module.ts:**
![04  core module ts](https://user-images.githubusercontent.com/22094979/94840284-dd1c0e00-0420-11eb-9da4-9fc7f4f18573.png)

**core.state.ts:**
![05  core state ts](https://user-images.githubusercontent.com/22094979/94840303-e4431c00-0420-11eb-94fd-9637c73de07e.png)

**settings.model.ts:**
![06  settings model ts](https://user-images.githubusercontent.com/22094979/94840312-e86f3980-0420-11eb-8428-090a445853d8.png)

**selector.ts:**
![07  selector ts](https://user-images.githubusercontent.com/22094979/94840334-eefdb100-0420-11eb-80f9-401cd640a22f.png)

**settings.reducer.ts:**
![08  settings reducer ts](https://user-images.githubusercontent.com/22094979/94840349-f329ce80-0420-11eb-8081-204e926c1e2d.png)

**settings.actions.ts:**
![09  settings actions ts](https://user-images.githubusercontent.com/22094979/94840368-fae97300-0420-11eb-9d31-c0af2899bd66.png)

**tsconfig.json:**
![10  tsconfig json](https://user-images.githubusercontent.com/22094979/94840417-105e9d00-0421-11eb-98ea-1f9d6019ab13.png)

**package.json:**
![11  package json](https://user-images.githubusercontent.com/22094979/94840426-15235100-0421-11eb-861d-01d8469a0b2c.png)

**Comment by Zaky7** [comment]
can you share a stackblitz or code so that I take a loot into it?

**Comment by Danubius1st** [comment]
What I try is here:
`git clone https://Crysis3@bitbucket.org/Crysis3/starter.git`
Thanks

**Comment by Danubius1st** [comment]
> can you share a stackblitz or code so that I take a loot into it?

`git clone https://Crysis3@bitbucket.org/Crysis3/starter.git`
Thanks

**Comment by Zaky7** [comment]
The code you shared had only default angular code. I had to recreate the code from the screen shot provided. But I did not get the error. May be you can have look at my code https://github.com/Zaky7/NgRxStarterSample. 

Or you need to check the dependency of your project.

**Comment by Danubius1st** [comment]
> @Danubius1st The code you shared had only default angular code. I had to recreate the code from the screen shot provided. But I did not get the error. May be you can have look at my code https://github.com/Zaky7/NgRxStarterSample.
> 
> Or you need to check the dependency of your project.

**Comment by Danubius1st** [comment]
Awesome! Thanks! 🥇

**Comment by tomastrajan** [comment]
@Zaky7 thanks for help mate!
