### ISSUE TITLE
link leads to 404 github page. README.md file 

### ISSUE THREAD

**Issue by omarbenzi** [tomastrajan/angular-ngrx-material-starter#556]
**Footer link**
  <img width="1080" alt="Screen Shot 2021-07-15 at 3 22 08 PM" src="https://user-images.githubusercontent.com/52929955/125845505-113d34d2-62bc-4257-a779-1bb38ab59efc.png">

**Comment by tino-tg** [comment]
@omarbenzi  thanks for submitting the issue --> fix is on the way
