### ISSUE TITLE
matInput colors for Dark Theme are incorrect

### ISSUE THREAD

**Issue by elucidsoft** [tomastrajan/angular-ngrx-material-starter#70]
The matInput colors for Dark theme are not right, they show up as black when focused.  I dug around and wasn't 100% clear on how this should be fixed properly.  It looks like setting the 900 on mat-palette($mat-grey, 900...) in the first parameter is responsible.  But if you change that it also changes the navbar, etc.  

I was able to override these settings in styles.reset.scss-theme.scss with the following:
```
 .mat-focused {
    .mat-form-field-label {
      color: mat-color($accent, lighter) !important;
    }

    .mat-form-field-ripple {
      background-color: mat-color($accent, lighter);
    }
  }
```

But that seems kind of like a hack and not proper.  I also didn't fix the cursor color in that fix, just the ripple, and the field label.  For a proper fix you would also want to address the cursor color.

**Comment by JosepAlacid** [comment]
Cant' understand why this is closed without any comment or solution.
Sorry if I didn't been able to find the answer.

**Comment by tomastrajan** [comment]
@JosepAlacid I don't remember in particular but I guess at that time I though it was fixed by that referenced commit, its almost a year ago so I don't remember the details. Is this still an issue? Can you submit a fix?
