### ISSUE TITLE
Animation does not work well on  Ms Edge browser

### ISSUE THREAD

**Issue by rurziceanu** [tomastrajan/angular-ngrx-material-starter#71]
Hello,
Do you have a solution to fix the issue with the animation on edge browser?
all content is to the left and then after the animation has finished it goes to the center

**Comment by tomastrajan** [comment]
This was already dealt with oncr but it seem this bug returned, it has something to do with flex layout (the main layout) of the content and footer. 

I'll look into it later but maybe you can try some width 100% or jusy google for IE / Edge flexbox width glitch.

**Comment by rurziceanu** [comment]
thx :) I will try
And thank you for sharing this project

**Comment by rurziceanu** [comment]
From what I've seen, is not related to flex main layout
I fixed it by adding a wrapper div in the pages with position relative

**Comment by tomastrajan** [comment]
Could you please share solution by creating a  PR with the fix ?

**Comment by rurziceanu** [comment]
Sure, 
But I see that I don't have the rights to create a branch for the pull request 
![capture](https://user-images.githubusercontent.com/33427578/37922004-b71273f4-312b-11e8-9df6-f947b1fa4d66.PNG)

**Comment by tomastrajan** [comment]
Hmm, the way this usualy work is to create a `fork` of the repository, then create branch with fix and push it to the fork. Github then offers creation of pull request automatically when checking branch on the web.
Hope that helps :)

**Comment by tomastrajan** [comment]
Hey @rurziceanu  !

Could you please share fix at least here in comment?

Thank you!

**Comment by rurziceanu** [comment]
Hi,
Sorry, I did not had time for this..
But the fix is in the animation definition 

export const routerTransition = trigger('routerTransition', [
  transition('* <=> *', [
    query(':enter > *', style({ opacity: 0, position: 'absolute', left: 0, right: 0 }), {
      optional: true
    }),
    query(':enter .' + ANIMATE_ON_ROUTE_ENTER, style({ opacity: '0' }), {
      optional: true
    }),
    sequence([
      query(
        ':leave > *',
        [
          style({ transform: 'translateY(0%)', opacity: 1 }),
          animate(
            '0.2s ease-in-out',
            style({ transform: 'translateY(-3%)', opacity: 0 })
          ),
          style({ position: 'absolute', left: 0, right: 0 })
        ],
        { optional: true }
      ),
      query(
        ':enter > *',
        [
          style({
            transform: 'translateY(-3%)',
            opacity: '0',
            position: 'absolute', left: 0, right: 0
          }),
          animate(
            '0.5s ease-in-out',
            style({ transform: 'translateY(0%)', opacity: 1 })
          )
        ],
        { optional: true }
      )
    ]),
    query(
      ':enter .' + ANIMATE_ON_ROUTE_ENTER,
      stagger(100, [
        style({ transform: 'translateY(15%)', opacity: 0 }),
        animate(
          '0.5s ease-in-out',
          style({ transform: 'translateY(0%)', opacity: 1 })
        )
      ]),
      { optional: true }
    )
  ])
]);

and then make sure that the container has position relative

**Comment by tomastrajan** [comment]
The stuff from comment unfortunately didn't really work. Partially disabling animation (removing whole page slide-in but still KEEPING the individual element slide-ups) solves this issue.

Preserved animations still look pretty great in IE and Edge.
Chrome / Firefox users can enjoy full experience.
