### ISSUE TITLE
MatSnackBar Theme missing

### ISSUE THREAD

**Issue by elucidsoft** [tomastrajan/angular-ngrx-material-starter#72]
Also noticed that there is no theme applied to SnackBars when used.

**Comment by tomastrajan** [comment]
Hey @elucidsoft !

I added example on how to style todos notification snack bar... 

The gist of it is that it is an overlay component (similar to menu popup or dialog) so the popup part ( the notification itself ) is added to the end of the DOM tree just before closing `</body>` tag. This means that the layout doesn't belong to the todos component itself and has to be styled using global styles in `todos.component.scss-theme.scss` with global css class selector `.todos-notification-overlay` which was passed in configuration of the snack-bar.

Hope that helps!

That being said, I consider snack-bar pretty lacking in terms of customization and would be in favor of using custom notification service ( in `CoreModule` ) and corresponding `NotificationComponent` which will implement stuff like severity (eg `info`, `warn`, `error`, `success` ) and more complex action handling...

Cheers!

**Comment by elucidsoft** [comment]
I would also be in favor of such a component to replace snackbar...
